//
//  ContentView.swift
//  JobHuntTracker
//
//  Created by user248930 on 11/14/23.
//

import SwiftUI
import CoreData


struct JobApplicationsListView: View {
    
        @Environment(\.managedObjectContext) private var viewContext
    
        @FetchRequest(
            sortDescriptors: [NSSortDescriptor(keyPath: \JobApplicationEntity.applicationDate, ascending: true)],
            animation: .default)
    private var jobApplications: FetchedResults<JobApplicationEntity>

//    let applications: [JobApplication] = [
//        // Sample data
//        .init(companyName: "Company A", jobTitle: "Software Engineer", applicationDate: "Jan 1, 2023", status: "Applied", logoName: "logo1"),
//        .init(companyName: "Company B", jobTitle: "Product Manager", applicationDate: "Feb 15, 2023", status: "Interviewing", logoName: "logo2"),
//    ]

    var body: some View {
        NavigationStack {
            VStack(spacing: 40) {
                // Upper element view
                ProfileOverviewView(userName: "Hus", userTitle: "iOS Developer", applicationsThisMonth: 5, monthlyTarget: 10)
                    .padding(.horizontal)
                
                TopStatusView()
                
                // List of job applications
                
                List(jobApplications,  id: \.self) { jobApplication in
                            JobApplicationRow(application: jobApplication)
                                .listRowSeparator(.hidden)
//                            Doing this to remove the right arrow generated by NavigationLink for some reason
                                .background(
                                          NavigationLink("", destination:  JobApplicationDetailsView(jobApplication: jobApplication))
                                              .opacity(0)
                                      )
                        }

                .navigationTitle("Jobs")

                .listStyle(PlainListStyle())
                .background(Color.orange)
                                .cornerRadius(20)
                                .edgesIgnoringSafeArea(.bottom)
                                .padding(.top, -20)
                
            }
            .navigationBarItems(
                leading: Button(action: {}) {
                    Image(systemName: "line.horizontal.3.decrease.circle.fill")
                },
                trailing: Button(action: addJobApplication) {
                               Image(systemName: "plus.circle.fill")
                           }
            )
        }
        .background(Color.white)
    }
    
    private func addJobApplication() {
          withAnimation {
              let newJobApplication = JobApplicationEntity(context: viewContext)
              newJobApplication.companyName = "New Company"
              newJobApplication.jobTitle = "New Position"
              newJobApplication.applicationDate = Date()
              newJobApplication.status = "Applied"
              // Set other properties as needed

              do {
                  try viewContext.save()
              } catch {
                  // Handle the error appropriately
                  let nsError = error as NSError
                  fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
              }
          }
      }
    
    private func deleteItems(offsets: IndexSet) {
        withAnimation {
            offsets.map { jobApplications[$0] }.forEach(viewContext.delete)

            do {
                try viewContext.save()
            } catch {
                // Replace this implementation with code to handle the error appropriately.
                let nsError = error as NSError
                fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
            }
        }
    }
}


struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        JobApplicationsListView()
    }}

//struct ContentView: View {
//    @Environment(\.managedObjectContext) private var viewContext
//
//    @FetchRequest(
//        sortDescriptors: [NSSortDescriptor(keyPath: \Item.timestamp, ascending: true)],
//        animation: .default)
//    private var items: FetchedResults<Item>

//    var body: some View {
//        NavigationView {
//            List {
//                ForEach(items) { item in
//                    NavigationLink {
//                        Text("Item at \(item.timestamp!, formatter: itemFormatter)")
//                    } label: {
//                        Text(item.timestamp!, formatter: itemFormatter)
//                    }
//                }
//                .onDelete(perform: deleteItems)
//            }
//            .toolbar {
//                ToolbarItem(placement: .navigationBarTrailing) {
//                    EditButton()
//                }
//                ToolbarItem {
//                    Button(action: addItem) {
//                        Label("Add Item", systemImage: "plus")
//                    }
//                }
//            }
//            Text("Select an item")
//        }
//    }

//    private func addItem() {
//        withAnimation {
//            let newItem = Item(context: viewContext)
//            newItem.timestamp = Date()
//
//            do {
//                try viewContext.save()
//            } catch {
//                // Replace this implementation with code to handle the error appropriately.
//                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
//                let nsError = error as NSError
//                fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
//            }
//        }
//    }
//
//    private func deleteItems(offsets: IndexSet) {
//        withAnimation {
//            offsets.map { items[$0] }.forEach(viewContext.delete)
//
//            do {
//                try viewContext.save()
//            } catch {
//                // Replace this implementation with code to handle the error appropriately.
//                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
//                let nsError = error as NSError
//                fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
//            }
//        }
//    }
//}

//private let itemFormatter: DateFormatter = {
//    let formatter = DateFormatter()
//    formatter.dateStyle = .short
//    formatter.timeStyle = .medium
//    return formatter
//}()



